//! End-to-end encryption for Horcrux transport channels.
//!
//! Provides authenticated encryption between two devices so that the relay
//! server (or any network observer) cannot read or tamper with messages.
//!
//! Protocol:
//!   1. Each device generates an X25519 keypair (ephemeral per session)
//!   2. Devices exchange public keys via a trusted channel (face-to-face QR,
//!      BLE, or pre-shared out-of-band)
//!   3. Shared secret is derived via X25519 DH → HKDF-SHA256
//!   4. All messages are encrypted with AES-256-GCM using the derived key
//!   5. Each message is signed with the sender's Ed25519 identity key
//!      so the recipient can verify authenticity (anti-MITM)

use aes_gcm::{Aes256Gcm, Key, Nonce};
use aes_gcm::aead::{Aead, KeyInit};
use hkdf::Hkdf;
use rand::RngCore;
use sha2::Sha256;
use x25519_dalek::{EphemeralSecret, PublicKey, SharedSecret};
use ed25519_dalek::{SigningKey, VerifyingKey, Signature, Signer, Verifier};
use serde::{Deserialize, Serialize};
use zeroize::Zeroize;

const NONCE_SIZE: usize = 12;
const KEY_SIZE: usize = 32;

/// An E2E encrypted + signed message ready for transport.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SealedEnvelope {
    /// Sender's Ed25519 public key (32 bytes) — identity verification
    pub sender_identity: Vec<u8>,
    /// Sender's X25519 ephemeral public key (32 bytes) — for initial handshake
    /// Only present in the first message (key exchange phase).
    pub ephemeral_pubkey: Option<Vec<u8>>,
    /// AES-256-GCM nonce (12 bytes)
    pub nonce: Vec<u8>,
    /// AES-256-GCM ciphertext (encrypted payload + auth tag)
    pub ciphertext: Vec<u8>,
    /// Ed25519 signature over (nonce || ciphertext) — proves sender identity
    pub signature: Vec<u8>,
    /// Monotonic sequence number (included in AAD to prevent replay/reorder)
    pub seq: u64,
}

/// Session token for room access control.
/// Generated by the session initiator and shared with participants via a
/// trusted channel (QR code, BLE, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionToken {
    /// Random 32-byte room secret
    pub room_secret: Vec<u8>,
    /// HMAC of room_id derived from room_secret — used as room access token
    pub access_token: Vec<u8>,
    /// Room ID (derived from room_secret)
    pub room_id: String,
}

/// Manages the E2E encrypted channel state for one peer.
pub struct E2EChannel {
    /// Our Ed25519 signing key (identity)
    our_signing_key: SigningKey,
    /// Peer's Ed25519 verifying key (identity)
    peer_verifying_key: Option<VerifyingKey>,
    /// Derived AES-256 symmetric key from X25519 DH
    symmetric_key: Option<[u8; KEY_SIZE]>,
    /// Message sequence counter
    seq_counter: u64,
    /// Highest sequence number seen from peer (replay protection)
    peer_max_seq: u64,
}

impl E2EChannel {
    /// Create a new E2E channel with a fresh identity.
    pub fn new() -> Self {
        let signing_key = SigningKey::generate(&mut rand::thread_rng());
        Self {
            our_signing_key: signing_key,
            peer_verifying_key: None,
            symmetric_key: None,
            seq_counter: 0,
            peer_max_seq: 0,
        }
    }

    /// Create from an existing Ed25519 signing key.
    pub fn from_identity(signing_key: SigningKey) -> Self {
        Self {
            our_signing_key: signing_key,
            peer_verifying_key: None,
            symmetric_key: None,
            seq_counter: 0,
            peer_max_seq: 0,
        }
    }

    /// Our Ed25519 public identity key (for sharing with peers).
    pub fn our_identity(&self) -> Vec<u8> {
        self.our_signing_key.verifying_key().to_bytes().to_vec()
    }

    /// Set the peer's identity key (must be verified out-of-band for MITM resistance).
    pub fn set_peer_identity(&mut self, peer_pubkey: &[u8]) -> Result<(), E2EError> {
        let bytes: [u8; 32] = peer_pubkey.try_into()
            .map_err(|_| E2EError::InvalidKey("peer identity must be 32 bytes".into()))?;
        let vk = VerifyingKey::from_bytes(&bytes)
            .map_err(|e| E2EError::InvalidKey(format!("invalid ed25519 key: {}", e)))?;
        self.peer_verifying_key = Some(vk);
        Ok(())
    }

    /// Perform X25519 key exchange. Returns our ephemeral public key.
    /// Call this, send the public key to the peer, then call `complete_handshake`
    /// with the peer's ephemeral public key.
    pub fn begin_handshake(&self) -> (EphemeralSecret, Vec<u8>) {
        let secret = EphemeralSecret::random_from_rng(rand::thread_rng());
        let public = PublicKey::from(&secret);
        (secret, public.to_bytes().to_vec())
    }

    /// Complete the handshake with the peer's X25519 public key.
    /// Derives the shared symmetric key via HKDF.
    pub fn complete_handshake(
        &mut self,
        our_secret: EphemeralSecret,
        peer_x25519_pubkey: &[u8],
        session_context: &[u8],
    ) -> Result<(), E2EError> {
        let peer_bytes: [u8; 32] = peer_x25519_pubkey.try_into()
            .map_err(|_| E2EError::InvalidKey("X25519 public key must be 32 bytes".into()))?;
        let peer_public = PublicKey::from(peer_bytes);

        let shared_secret: SharedSecret = our_secret.diffie_hellman(&peer_public);

        // Derive AES key via HKDF with session context as info
        let hk = Hkdf::<Sha256>::new(None, shared_secret.as_bytes());
        let mut key = [0u8; KEY_SIZE];
        hk.expand(session_context, &mut key)
            .map_err(|_| E2EError::KeyDerivation("HKDF expand failed".into()))?;

        self.symmetric_key = Some(key);
        self.seq_counter = 0;
        self.peer_max_seq = 0;

        Ok(())
    }

    /// Set symmetric key directly (for testing or when key is pre-shared).
    pub fn set_symmetric_key(&mut self, key: [u8; KEY_SIZE]) {
        self.symmetric_key = Some(key);
    }

    /// Encrypt and sign a message.
    pub fn seal(&mut self, plaintext: &[u8]) -> Result<SealedEnvelope, E2EError> {
        let key = self.symmetric_key
            .as_ref()
            .ok_or(E2EError::NoSession)?;

        let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));

        let mut nonce_bytes = [0u8; NONCE_SIZE];
        rand::thread_rng().fill_bytes(&mut nonce_bytes);
        let nonce = Nonce::from_slice(&nonce_bytes);

        // Additional authenticated data: sequence number (prevents replay/reorder)
        let seq = self.seq_counter;
        self.seq_counter += 1;

        // Encrypt with AAD = seq as big-endian bytes
        let aad = seq.to_be_bytes();
        let ciphertext = cipher
            .encrypt(nonce, aes_gcm::aead::Payload { msg: plaintext, aad: &aad })
            .map_err(|e| E2EError::Encryption(format!("AES-GCM encrypt failed: {}", e)))?;

        // Sign (nonce || ciphertext || seq) with our Ed25519 key
        let mut sign_data = Vec::with_capacity(NONCE_SIZE + ciphertext.len() + 8);
        sign_data.extend_from_slice(&nonce_bytes);
        sign_data.extend_from_slice(&ciphertext);
        sign_data.extend_from_slice(&aad);
        let signature = self.our_signing_key.sign(&sign_data);

        Ok(SealedEnvelope {
            sender_identity: self.our_identity(),
            ephemeral_pubkey: None,
            nonce: nonce_bytes.to_vec(),
            ciphertext,
            signature: signature.to_bytes().to_vec(),
            seq,
        })
    }

    /// Verify signature and decrypt a message.
    pub fn open(&mut self, envelope: &SealedEnvelope) -> Result<Vec<u8>, E2EError> {
        let key = self.symmetric_key
            .as_ref()
            .ok_or(E2EError::NoSession)?;

        // Verify sender identity
        let peer_vk = self.peer_verifying_key
            .as_ref()
            .ok_or(E2EError::NoPeerIdentity)?;

        // Check that sender_identity matches our known peer
        let sender_bytes: [u8; 32] = envelope.sender_identity.clone().try_into()
            .map_err(|_| E2EError::InvalidKey("sender identity bad size".into()))?;
        let sender_vk = VerifyingKey::from_bytes(&sender_bytes)
            .map_err(|_| E2EError::InvalidKey("invalid sender identity".into()))?;
        if sender_vk != *peer_vk {
            return Err(E2EError::IdentityMismatch);
        }

        // Replay protection: sequence must be strictly increasing
        if envelope.seq <= self.peer_max_seq && self.peer_max_seq > 0 {
            return Err(E2EError::ReplayDetected(envelope.seq));
        }

        // Verify signature
        let aad = envelope.seq.to_be_bytes();
        let mut sign_data = Vec::with_capacity(envelope.nonce.len() + envelope.ciphertext.len() + 8);
        sign_data.extend_from_slice(&envelope.nonce);
        sign_data.extend_from_slice(&envelope.ciphertext);
        sign_data.extend_from_slice(&aad);

        let sig_bytes: [u8; 64] = envelope.signature.clone().try_into()
            .map_err(|_| E2EError::InvalidSignature("signature must be 64 bytes".into()))?;
        let signature = Signature::from_bytes(&sig_bytes);

        peer_vk.verify(&sign_data, &signature)
            .map_err(|_| E2EError::InvalidSignature("Ed25519 verification failed".into()))?;

        // Decrypt
        let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
        let nonce = Nonce::from_slice(&envelope.nonce);

        let plaintext = cipher
            .decrypt(nonce, aes_gcm::aead::Payload { msg: &envelope.ciphertext, aad: &aad })
            .map_err(|e| E2EError::Decryption(format!("AES-GCM decrypt failed: {}", e)))?;

        self.peer_max_seq = envelope.seq;

        Ok(plaintext)
    }
}

impl Drop for E2EChannel {
    fn drop(&mut self) {
        if let Some(ref mut key) = self.symmetric_key {
            key.zeroize();
        }
    }
}

// --- Session Token ---

impl SessionToken {
    /// Generate a new random session token.
    pub fn generate() -> Self {
        let mut room_secret = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut room_secret);

        // Derive room_id from secret (first 16 bytes of HKDF, hex-encoded)
        let hk = Hkdf::<Sha256>::new(None, &room_secret);
        let mut room_id_bytes = [0u8; 16];
        hk.expand(b"horcrux-room-id", &mut room_id_bytes).unwrap();
        let room_id = hex::encode(&room_id_bytes);

        // Derive access token
        let mut access_bytes = [0u8; 32];
        hk.expand(b"horcrux-access-token", &mut access_bytes).unwrap();

        Self {
            room_secret: room_secret.to_vec(),
            access_token: access_bytes.to_vec(),
            room_id,
        }
    }

    /// Verify that an access token is valid for this session.
    pub fn verify_access(&self, token: &[u8]) -> bool {
        // Constant-time comparison
        if token.len() != self.access_token.len() {
            return false;
        }
        let mut diff = 0u8;
        for (a, b) in token.iter().zip(self.access_token.iter()) {
            diff |= a ^ b;
        }
        diff == 0
    }
}

#[derive(Debug, thiserror::Error)]
pub enum E2EError {
    #[error("invalid key: {0}")]
    InvalidKey(String),
    #[error("key derivation failed: {0}")]
    KeyDerivation(String),
    #[error("no E2E session established")]
    NoSession,
    #[error("peer identity not set")]
    NoPeerIdentity,
    #[error("sender identity does not match known peer")]
    IdentityMismatch,
    #[error("encryption failed: {0}")]
    Encryption(String),
    #[error("decryption failed: {0}")]
    Decryption(String),
    #[error("invalid signature: {0}")]
    InvalidSignature(String),
    #[error("replay detected: seq {0}")]
    ReplayDetected(u64),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_e2e_channel_roundtrip() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();

        // Exchange identities (in real usage, verified face-to-face or via QR)
        bob.set_peer_identity(&alice.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        // X25519 handshake
        let (alice_secret, alice_pubkey) = alice.begin_handshake();
        let (bob_secret, bob_pubkey) = bob.begin_handshake();

        let context = b"horcrux-e2e-test-session";
        alice.complete_handshake(alice_secret, &bob_pubkey, context).unwrap();
        bob.complete_handshake(bob_secret, &alice_pubkey, context).unwrap();

        // Alice sends to Bob
        let message = b"Hello from Alice! This is a secret MPC message.";
        let sealed = alice.seal(message).unwrap();

        // Verify it's actually encrypted (ciphertext != plaintext)
        assert_ne!(sealed.ciphertext, message.to_vec());

        // Bob opens
        let decrypted = bob.open(&sealed).unwrap();
        assert_eq!(decrypted, message.to_vec());
    }

    #[test]
    fn test_e2e_bidirectional() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();

        bob.set_peer_identity(&alice.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        let (as_, ap) = alice.begin_handshake();
        let (bs, bp) = bob.begin_handshake();
        alice.complete_handshake(as_, &bp, b"session").unwrap();
        bob.complete_handshake(bs, &ap, b"session").unwrap();

        // Alice → Bob
        let sealed1 = alice.seal(b"msg from alice").unwrap();
        assert_eq!(bob.open(&sealed1).unwrap(), b"msg from alice");

        // Bob → Alice
        let sealed2 = bob.seal(b"msg from bob").unwrap();
        assert_eq!(alice.open(&sealed2).unwrap(), b"msg from bob");
    }

    #[test]
    fn test_e2e_tampered_ciphertext_rejected() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();

        bob.set_peer_identity(&alice.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        let (as_, ap) = alice.begin_handshake();
        let (bs, bp) = bob.begin_handshake();
        alice.complete_handshake(as_, &bp, b"s").unwrap();
        bob.complete_handshake(bs, &ap, b"s").unwrap();

        let mut sealed = alice.seal(b"secret").unwrap();
        // Tamper with ciphertext
        if let Some(byte) = sealed.ciphertext.first_mut() {
            *byte ^= 0xFF;
        }

        // Bob should reject — either signature fails or AEAD fails
        assert!(bob.open(&sealed).is_err());
    }

    #[test]
    fn test_e2e_wrong_identity_rejected() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();
        let eve = E2EChannel::new();

        // Bob thinks he's talking to Eve, not Alice
        bob.set_peer_identity(&eve.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        let (as_, ap) = alice.begin_handshake();
        let (bs, bp) = bob.begin_handshake();
        alice.complete_handshake(as_, &bp, b"s").unwrap();
        bob.complete_handshake(bs, &ap, b"s").unwrap();

        let sealed = alice.seal(b"hello").unwrap();
        // Bob rejects because sender_identity is Alice, not Eve
        let result = bob.open(&sealed);
        assert!(result.is_err());
        match result.unwrap_err() {
            E2EError::IdentityMismatch => {} // expected
            other => panic!("expected IdentityMismatch, got {:?}", other),
        }
    }

    #[test]
    fn test_e2e_replay_rejected() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();

        bob.set_peer_identity(&alice.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        let (as_, ap) = alice.begin_handshake();
        let (bs, bp) = bob.begin_handshake();
        alice.complete_handshake(as_, &bp, b"s").unwrap();
        bob.complete_handshake(bs, &ap, b"s").unwrap();

        let sealed1 = alice.seal(b"msg 1").unwrap();
        let sealed2 = alice.seal(b"msg 2").unwrap();

        // Process in order
        bob.open(&sealed1).unwrap();
        bob.open(&sealed2).unwrap();

        // Replay sealed1 — should be rejected (seq too low)
        let result = bob.open(&sealed1);
        assert!(result.is_err());
        match result.unwrap_err() {
            E2EError::ReplayDetected(_) => {} // expected
            other => panic!("expected ReplayDetected, got {:?}", other),
        }
    }

    #[test]
    fn test_e2e_no_session_fails() {
        let mut alice = E2EChannel::new();
        // No handshake done
        assert!(alice.seal(b"test").is_err());
    }

    #[test]
    fn test_session_token_generation() {
        let token = SessionToken::generate();
        assert_eq!(token.room_secret.len(), 32);
        assert_eq!(token.access_token.len(), 32);
        assert_eq!(token.room_id.len(), 32); // 16 bytes hex-encoded

        // Verify access
        assert!(token.verify_access(&token.access_token));
        assert!(!token.verify_access(&[0u8; 32]));
    }

    #[test]
    fn test_session_token_uniqueness() {
        let t1 = SessionToken::generate();
        let t2 = SessionToken::generate();
        assert_ne!(t1.room_id, t2.room_id);
        assert_ne!(t1.access_token, t2.access_token);
    }

    #[test]
    fn test_sealed_envelope_serialization() {
        let mut alice = E2EChannel::new();
        let mut bob = E2EChannel::new();

        bob.set_peer_identity(&alice.our_identity()).unwrap();
        alice.set_peer_identity(&bob.our_identity()).unwrap();

        let (as_, ap) = alice.begin_handshake();
        let (bs, bp) = bob.begin_handshake();
        alice.complete_handshake(as_, &bp, b"s").unwrap();
        bob.complete_handshake(bs, &ap, b"s").unwrap();

        let sealed = alice.seal(b"serialize me").unwrap();

        // Serialize to JSON (this is what goes over the wire)
        let json = serde_json::to_string(&sealed).unwrap();
        let deserialized: SealedEnvelope = serde_json::from_str(&json).unwrap();

        // Bob can still open the deserialized envelope
        let plaintext = bob.open(&deserialized).unwrap();
        assert_eq!(plaintext, b"serialize me");
    }
}
