//! End-to-end encryption for Horcrux transport channels using the
//! **Noise Protocol Framework** (Noise_XX pattern).
//!
//! This replaces the hand-rolled X25519 + AES-256-GCM + Ed25519 layer with
//! the same proven protocol used by **Signal**, **WireGuard**, and
//! **Lightning Network**.
//!
//! ## Why Noise_XX?
//!
//! - **XX pattern**: mutual authentication — both sides prove their identity
//!   via static Curve25519 keys, with full forward secrecy.
//! - **3-message handshake**: `→ e`, `← e, ee, s, es`, `→ s, se`
//! - After handshake, both sides hold `TransportState` with split
//!   CipherState pairs (ChaChaPoly-1305 by default).
//! - **Built-in replay protection** via internal nonce counters.
//! - **Forward secrecy**: ephemeral keys are discarded after handshake.
//!
//! ## Protocol flow
//!
//! 1. Each device generates a static Curve25519 keypair (persisted as identity).
//! 2. **Initiator** creates handshake, writes message 1 (`→ e`).
//! 3. **Responder** reads message 1, writes message 2 (`← e, ee, s, es`).
//! 4. **Initiator** reads message 2, writes message 3 (`→ s, se`).
//! 5. Both call `into_transport_mode()` — all subsequent messages are
//!    encrypted + authenticated with ChaChaPoly-1305.
//!
//! Static keys are exchanged out-of-band (QR code, BLE) for MITM resistance,
//! same as before.

use serde::{Deserialize, Serialize};
use snow::{Builder, HandshakeState, TransportState};
use subtle::ConstantTimeEq;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Noise protocol pattern: XX with Curve25519, ChaChaPoly, SHA-256.
/// XX = mutual authentication, both sides transmit their static key.
const NOISE_PATTERN: &str = "Noise_XX_25519_ChaChaPoly_SHA256";

/// Maximum Noise message overhead (for ChaChaPoly: 16 bytes MAC + handshake headers).
const MAX_NOISE_OVERHEAD: usize = 128;

/// An encrypted message ready for transport.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SealedEnvelope {
    /// Noise ciphertext (encrypted payload + MAC tag).
    pub ciphertext: Vec<u8>,
    /// Whether this is a handshake message (true) or transport message (false).
    pub handshake: bool,
}

/// Session token for room access control.
/// Generated by the session initiator and shared with participants via a
/// trusted channel (QR code, BLE, etc.).
#[derive(Debug, Clone, Serialize, Deserialize, Zeroize, ZeroizeOnDrop)]
pub struct SessionToken {
    /// Random 32-byte room secret
    pub room_secret: Vec<u8>,
    /// HMAC of room_id derived from room_secret — used as room access token
    pub access_token: Vec<u8>,
    /// Room ID (derived from room_secret)
    pub room_id: String,
}

/// Noise channel state — progresses from Handshake → Transport.
#[allow(clippy::large_enum_variant)]
pub enum NoiseChannel {
    /// Handshake in progress.
    Handshake(HandshakeState),
    /// Handshake complete — encrypted transport ready.
    Transport(TransportState),
}

/// Static keypair for Noise (Curve25519).
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct NoiseKeypair {
    pub private: Vec<u8>,
    pub public: Vec<u8>,
}

impl NoiseKeypair {
    /// Generate a fresh Curve25519 keypair.
    pub fn generate() -> Result<Self, E2EError> {
        let builder = Builder::new(
            NOISE_PATTERN
                .parse()
                .map_err(|e| E2EError::Handshake(format!("parse pattern: {e}")))?,
        );
        let kp = builder
            .generate_keypair()
            .map_err(|e| E2EError::Handshake(format!("generate keypair: {e}")))?;
        Ok(Self {
            private: kp.private,
            public: kp.public,
        })
    }
}

impl NoiseChannel {
    /// Create an initiator (the device that starts the handshake).
    /// `local_keypair`: our persistent Curve25519 identity.
    pub fn initiator(local_keypair: &NoiseKeypair) -> Result<Self, E2EError> {
        let params = NOISE_PATTERN
            .parse()
            .map_err(|e| E2EError::Handshake(format!("parse pattern: {}", e)))?;
        let hs = Builder::new(params)
            .local_private_key(&local_keypair.private)
            .map_err(|e| E2EError::Handshake(format!("set key: {}", e)))?
            .build_initiator()
            .map_err(|e| E2EError::Handshake(format!("build initiator: {}", e)))?;
        Ok(NoiseChannel::Handshake(hs))
    }

    /// Create a responder (the device that receives the first handshake message).
    /// `local_keypair`: our persistent Curve25519 identity.
    pub fn responder(local_keypair: &NoiseKeypair) -> Result<Self, E2EError> {
        let params = NOISE_PATTERN
            .parse()
            .map_err(|e| E2EError::Handshake(format!("parse pattern: {}", e)))?;
        let hs = Builder::new(params)
            .local_private_key(&local_keypair.private)
            .map_err(|e| E2EError::Handshake(format!("set key: {}", e)))?
            .build_responder()
            .map_err(|e| E2EError::Handshake(format!("build responder: {}", e)))?;
        Ok(NoiseChannel::Handshake(hs))
    }

    /// Write a handshake message (or empty payload during handshake).
    /// Returns the message to send to the peer.
    pub fn write_handshake(&mut self, payload: &[u8]) -> Result<Vec<u8>, E2EError> {
        match self {
            NoiseChannel::Handshake(hs) => {
                let mut buf = vec![0u8; payload.len() + MAX_NOISE_OVERHEAD + 256];
                let len = hs
                    .write_message(payload, &mut buf)
                    .map_err(|e| E2EError::Handshake(format!("write: {}", e)))?;
                buf.truncate(len);
                Ok(buf)
            }
            NoiseChannel::Transport(_) => Err(E2EError::HandshakeComplete),
        }
    }

    /// Read a handshake message from the peer.
    /// Returns the decrypted payload (often empty during handshake).
    pub fn read_handshake(&mut self, message: &[u8]) -> Result<Vec<u8>, E2EError> {
        match self {
            NoiseChannel::Handshake(hs) => {
                let mut buf = vec![0u8; message.len() + MAX_NOISE_OVERHEAD];
                let len = hs
                    .read_message(message, &mut buf)
                    .map_err(|e| E2EError::Handshake(format!("read: {}", e)))?;
                buf.truncate(len);
                Ok(buf)
            }
            NoiseChannel::Transport(_) => Err(E2EError::HandshakeComplete),
        }
    }

    /// Check if the handshake is complete and ready to transition.
    pub fn is_handshake_finished(&self) -> bool {
        match self {
            NoiseChannel::Handshake(hs) => hs.is_handshake_finished(),
            NoiseChannel::Transport(_) => true,
        }
    }

    /// Transition from handshake to transport mode.
    /// Must be called after the handshake is complete.
    pub fn into_transport(self) -> Result<Self, E2EError> {
        match self {
            NoiseChannel::Handshake(hs) => {
                if !hs.is_handshake_finished() {
                    return Err(E2EError::HandshakeIncomplete);
                }
                let ts = hs
                    .into_transport_mode()
                    .map_err(|e| E2EError::Handshake(format!("transport transition: {}", e)))?;
                Ok(NoiseChannel::Transport(ts))
            }
            NoiseChannel::Transport(_) => Ok(self), // already in transport mode
        }
    }

    /// Get the remote peer's static public key (available after handshake).
    pub fn remote_static_key(&self) -> Option<Vec<u8>> {
        match self {
            NoiseChannel::Handshake(hs) => hs.get_remote_static().map(|k| k.to_vec()),
            NoiseChannel::Transport(ts) => ts.get_remote_static().map(|k| k.to_vec()),
        }
    }

    /// Encrypt a message (transport mode only).
    pub fn seal(&mut self, plaintext: &[u8]) -> Result<SealedEnvelope, E2EError> {
        match self {
            NoiseChannel::Transport(ts) => {
                let mut buf = vec![0u8; plaintext.len() + 16]; // 16 bytes for ChaChaPoly MAC
                let len = ts
                    .write_message(plaintext, &mut buf)
                    .map_err(|e| E2EError::Encryption(format!("{}", e)))?;
                buf.truncate(len);
                Ok(SealedEnvelope {
                    ciphertext: buf,
                    handshake: false,
                })
            }
            NoiseChannel::Handshake(_) => Err(E2EError::HandshakeIncomplete),
        }
    }

    /// Decrypt a message (transport mode only).
    pub fn open(&mut self, envelope: &SealedEnvelope) -> Result<Vec<u8>, E2EError> {
        if envelope.handshake {
            return Err(E2EError::Handshake(
                "unexpected handshake message in transport mode".into(),
            ));
        }
        match self {
            NoiseChannel::Transport(ts) => {
                let mut buf = vec![0u8; envelope.ciphertext.len()];
                let len = ts
                    .read_message(&envelope.ciphertext, &mut buf)
                    .map_err(|e| E2EError::Decryption(format!("{}", e)))?;
                buf.truncate(len);
                Ok(buf)
            }
            NoiseChannel::Handshake(_) => Err(E2EError::HandshakeIncomplete),
        }
    }
}

// --- Convenience: full XX handshake helper ---

/// Perform a complete Noise_XX handshake between initiator and responder.
/// Returns both channels in transport mode.
///
/// This is a helper for testing and for face-to-face (synchronous) channels.
/// For async relay usage, use the step-by-step write/read_handshake methods.
pub fn complete_xx_handshake(
    initiator_key: &NoiseKeypair,
    responder_key: &NoiseKeypair,
) -> Result<(NoiseChannel, NoiseChannel), E2EError> {
    let mut initiator = NoiseChannel::initiator(initiator_key)?;
    let mut responder = NoiseChannel::responder(responder_key)?;

    // → e
    let msg1 = initiator.write_handshake(&[])?;
    responder.read_handshake(&msg1)?;

    // ← e, ee, s, es
    let msg2 = responder.write_handshake(&[])?;
    initiator.read_handshake(&msg2)?;

    // → s, se
    let msg3 = initiator.write_handshake(&[])?;
    responder.read_handshake(&msg3)?;

    let initiator = initiator.into_transport()?;
    let responder = responder.into_transport()?;

    Ok((initiator, responder))
}

// --- Session Token (unchanged from before) ---

impl SessionToken {
    /// Generate a new random session token.
    /// Returns an error if HKDF expansion fails (should not happen with fixed-size outputs).
    pub fn generate() -> Result<Self, E2EError> {
        use hkdf::Hkdf;
        use rand::rngs::OsRng;
        use rand::RngCore;
        use sha2::Sha256;

        let mut room_secret = [0u8; 32];
        OsRng.fill_bytes(&mut room_secret);

        let hk = Hkdf::<Sha256>::new(None, &room_secret);
        let mut room_id_bytes = [0u8; 16];
        hk.expand(b"horcrux-room-id", &mut room_id_bytes)
            .map_err(|e| E2EError::Handshake(format!("HKDF expand for room ID failed: {e}")))?;
        let room_id = hex::encode(room_id_bytes);

        let mut access_bytes = [0u8; 32];
        hk.expand(b"horcrux-access-token", &mut access_bytes)
            .map_err(|e| {
                E2EError::Handshake(format!("HKDF expand for access token failed: {e}"))
            })?;

        Ok(Self {
            room_secret: room_secret.to_vec(),
            access_token: access_bytes.to_vec(),
            room_id,
        })
    }

    /// Verify that an access token is valid for this session.
    pub fn verify_access(&self, token: &[u8]) -> bool {
        token.ct_eq(&self.access_token).into()
    }
}

#[derive(Debug, thiserror::Error)]
pub enum E2EError {
    #[error("handshake error: {0}")]
    Handshake(String),
    #[error("handshake not yet complete")]
    HandshakeIncomplete,
    #[error("handshake already complete — use transport methods")]
    HandshakeComplete,
    #[error("encryption failed: {0}")]
    Encryption(String),
    #[error("decryption failed: {0}")]
    Decryption(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_noise_xx_handshake_and_roundtrip() {
        let alice_key = NoiseKeypair::generate().expect("keypair gen");
        let bob_key = NoiseKeypair::generate().expect("keypair gen");

        let (mut alice, mut bob) = complete_xx_handshake(&alice_key, &bob_key).unwrap();

        // Alice → Bob
        let msg = b"Hello from Alice via Noise!";
        let sealed = alice.seal(msg).unwrap();
        assert_ne!(sealed.ciphertext, msg.to_vec());
        assert!(!sealed.handshake);

        let decrypted = bob.open(&sealed).unwrap();
        assert_eq!(decrypted, msg.to_vec());
    }

    #[test]
    fn test_noise_bidirectional() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");
        let (mut a, mut b) = complete_xx_handshake(&ak, &bk).unwrap();

        // Alice → Bob
        let s1 = a.seal(b"msg from alice").unwrap();
        assert_eq!(b.open(&s1).unwrap(), b"msg from alice");

        // Bob → Alice
        let s2 = b.seal(b"msg from bob").unwrap();
        assert_eq!(a.open(&s2).unwrap(), b"msg from bob");

        // Multiple messages
        for i in 0..10 {
            let msg = format!("message {}", i);
            let s = a.seal(msg.as_bytes()).unwrap();
            assert_eq!(b.open(&s).unwrap(), msg.as_bytes());
        }
    }

    #[test]
    fn test_noise_tampered_ciphertext_rejected() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");
        let (mut a, mut b) = complete_xx_handshake(&ak, &bk).unwrap();

        let mut sealed = a.seal(b"secret data").unwrap();
        // Tamper with ciphertext
        if let Some(byte) = sealed.ciphertext.first_mut() {
            *byte ^= 0xFF;
        }

        assert!(b.open(&sealed).is_err());
    }

    #[test]
    fn test_noise_replay_rejected() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");
        let (mut a, mut b) = complete_xx_handshake(&ak, &bk).unwrap();

        let s1 = a.seal(b"msg 1").unwrap();
        let s2 = a.seal(b"msg 2").unwrap();

        // Process in order
        b.open(&s1).unwrap();
        b.open(&s2).unwrap();

        // Replay s1 — Noise's internal nonce counter rejects this
        // (ChaChaPoly nonce is incremented per message; replaying produces wrong nonce)
        assert!(b.open(&s1).is_err());
    }

    #[test]
    fn test_noise_wrong_key_cannot_decrypt() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");
        let ek = NoiseKeypair::generate().expect("keypair gen"); // Eve

        let (mut a, _b) = complete_xx_handshake(&ak, &bk).unwrap();

        // Eve creates her own session with her key — she can't decrypt Alice's messages
        let (_, mut eve) =
            complete_xx_handshake(&ek, &NoiseKeypair::generate().expect("keypair gen")).unwrap();

        let sealed = a.seal(b"for bob only").unwrap();
        assert!(eve.open(&sealed).is_err());
    }

    #[test]
    fn test_noise_mutual_authentication() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");

        let (a, b) = complete_xx_handshake(&ak, &bk).unwrap();

        // After XX handshake, both sides know each other's static key
        assert_eq!(a.remote_static_key().unwrap(), bk.public);
        assert_eq!(b.remote_static_key().unwrap(), ak.public);
    }

    #[test]
    fn test_noise_step_by_step_handshake() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");

        let mut initiator = NoiseChannel::initiator(&ak).unwrap();
        let mut responder = NoiseChannel::responder(&bk).unwrap();

        // Step 1: → e
        assert!(!initiator.is_handshake_finished());
        let msg1 = initiator.write_handshake(&[]).unwrap();

        responder.read_handshake(&msg1).unwrap();

        // Step 2: ← e, ee, s, es
        let msg2 = responder.write_handshake(&[]).unwrap();
        initiator.read_handshake(&msg2).unwrap();

        // Step 3: → s, se
        let msg3 = initiator.write_handshake(&[]).unwrap();
        responder.read_handshake(&msg3).unwrap();

        assert!(initiator.is_handshake_finished());
        assert!(responder.is_handshake_finished());

        let mut initiator = initiator.into_transport().unwrap();
        let mut responder = responder.into_transport().unwrap();

        // Now we can send encrypted messages
        let sealed = initiator.seal(b"step by step works!").unwrap();
        let plaintext = responder.open(&sealed).unwrap();
        assert_eq!(plaintext, b"step by step works!");
    }

    #[test]
    fn test_noise_handshake_with_payload() {
        // Noise XX allows embedding payloads in handshake messages
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");

        let mut initiator = NoiseChannel::initiator(&ak).unwrap();
        let mut responder = NoiseChannel::responder(&bk).unwrap();

        // → e (with payload)
        let msg1 = initiator.write_handshake(b"hello from initiator").unwrap();
        let payload1 = responder.read_handshake(&msg1).unwrap();
        assert_eq!(payload1, b"hello from initiator");

        // ← e, ee, s, es (with payload)
        let msg2 = responder.write_handshake(b"hello back").unwrap();
        let payload2 = initiator.read_handshake(&msg2).unwrap();
        assert_eq!(payload2, b"hello back");

        // → s, se
        let msg3 = initiator.write_handshake(b"ready").unwrap();
        let payload3 = responder.read_handshake(&msg3).unwrap();
        assert_eq!(payload3, b"ready");

        let mut initiator = initiator.into_transport().unwrap();
        let mut responder = responder.into_transport().unwrap();

        let s = initiator.seal(b"transport ok").unwrap();
        assert_eq!(responder.open(&s).unwrap(), b"transport ok");
    }

    #[test]
    fn test_seal_before_handshake_fails() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let mut ch = NoiseChannel::initiator(&ak).unwrap();
        assert!(ch.seal(b"too early").is_err());
    }

    #[test]
    fn test_sealed_envelope_serialization() {
        let ak = NoiseKeypair::generate().expect("keypair gen");
        let bk = NoiseKeypair::generate().expect("keypair gen");
        let (mut a, mut b) = complete_xx_handshake(&ak, &bk).unwrap();

        let sealed = a.seal(b"serialize me").unwrap();
        let json = serde_json::to_string(&sealed).unwrap();
        let deserialized: SealedEnvelope = serde_json::from_str(&json).unwrap();

        let plaintext = b.open(&deserialized).unwrap();
        assert_eq!(plaintext, b"serialize me");
    }

    #[test]
    fn test_session_token_generation() {
        let token = SessionToken::generate().unwrap();
        assert_eq!(token.room_secret.len(), 32);
        assert_eq!(token.access_token.len(), 32);
        assert_eq!(token.room_id.len(), 32);
        assert!(token.verify_access(&token.access_token));
        assert!(!token.verify_access(&[0u8; 32]));
    }

    #[test]
    fn test_session_token_uniqueness() {
        let t1 = SessionToken::generate().unwrap();
        let t2 = SessionToken::generate().unwrap();
        assert_ne!(t1.room_id, t2.room_id);
        assert_ne!(t1.access_token, t2.access_token);
    }
}

#[cfg(test)]
mod prop_tests {
    //! Property-based robustness for the Noise XX handshake parser.
    //!
    //! `read_handshake` is exposed to network-attacker-controlled bytes
    //! — a malformed / fuzzed / replayed frame from the relay or a
    //! misbehaving peer. These properties assert the responder never
    //! panics / UBs on arbitrary input up to 4 KiB, regardless of
    //! shape. Complements the focused unit tests (valid XX transcript,
    //! wrong-key rejection) with brute-force coverage of malformed
    //! input space.
    //!
    //! Companion fuzz harness at `horcrux-core/fuzz/fuzz_targets/` runs
    //! the same surface under libFuzzer coverage guidance for deeper
    //! exploration — see `docs/security-audit-2026-04.md` for the
    //! supply-chain + fuzz posture overview.
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #![proptest_config(ProptestConfig { cases: 256, ..ProptestConfig::default() })]

        /// Responder `read_handshake` must return `Err`, never panic,
        /// on arbitrary bytes. The snow state machine is the primary
        /// attack surface exposed to the relay / peer.
        #[test]
        fn prop_read_handshake_never_panics(bytes in prop::collection::vec(any::<u8>(), 0..4096)) {
            let kp = NoiseKeypair::generate().unwrap();
            let mut responder = NoiseChannel::responder(&kp).unwrap();
            // Result is either Ok(payload) or Err(_); either is fine, just no panic.
            let _ = responder.read_handshake(&bytes);
        }

        /// Responder must also reject truncated prefixes of a
        /// legitimate handshake message — a common malleability angle.
        #[test]
        fn prop_truncation_rejected(truncate_by in 1usize..=64) {
            let kp_i = NoiseKeypair::generate().unwrap();
            let kp_r = NoiseKeypair::generate().unwrap();
            let mut initiator = NoiseChannel::initiator(&kp_i).unwrap();
            let mut responder = NoiseChannel::responder(&kp_r).unwrap();
            let msg1 = initiator.write_handshake(&[]).unwrap();
            let cut = msg1.len().saturating_sub(truncate_by);
            let truncated = &msg1[..cut];
            // Either Ok (parser over-reads into nothing) or Err — but no panic.
            let _ = responder.read_handshake(truncated);
        }

        /// Full 3-round XX transcript with arbitrary payloads in each
        /// handshake round must complete, transition to transport mode,
        /// and round-trip an arbitrary application message both ways.
        /// This is the end-to-end "happy path" invariant under fuzzing.
        #[test]
        fn prop_full_handshake_roundtrip(
            hs_payload_1 in prop::collection::vec(any::<u8>(), 0..256),
            hs_payload_2 in prop::collection::vec(any::<u8>(), 0..256),
            hs_payload_3 in prop::collection::vec(any::<u8>(), 0..256),
            app_msg in prop::collection::vec(any::<u8>(), 0..4096),
        ) {
            let kp_i = NoiseKeypair::generate().unwrap();
            let kp_r = NoiseKeypair::generate().unwrap();
            let mut initiator = NoiseChannel::initiator(&kp_i).unwrap();
            let mut responder = NoiseChannel::responder(&kp_r).unwrap();

            // → e (+ optional payload)
            let m1 = initiator.write_handshake(&hs_payload_1).unwrap();
            let p1 = responder.read_handshake(&m1).unwrap();
            prop_assert_eq!(&p1, &hs_payload_1);

            // ← e, ee, s, es
            let m2 = responder.write_handshake(&hs_payload_2).unwrap();
            let p2 = initiator.read_handshake(&m2).unwrap();
            prop_assert_eq!(&p2, &hs_payload_2);

            // → s, se
            let m3 = initiator.write_handshake(&hs_payload_3).unwrap();
            let p3 = responder.read_handshake(&m3).unwrap();
            prop_assert_eq!(&p3, &hs_payload_3);

            let mut initiator = initiator.into_transport().unwrap();
            let mut responder = responder.into_transport().unwrap();

            // Transport-mode roundtrip both directions.
            let env = initiator.seal(&app_msg).unwrap();
            let decrypted = responder.open(&env).unwrap();
            prop_assert_eq!(&decrypted, &app_msg);

            let env2 = responder.seal(&app_msg).unwrap();
            let decrypted2 = initiator.open(&env2).unwrap();
            prop_assert_eq!(&decrypted2, &app_msg);
        }

        /// A single-bit tamper in the encrypted XX handshake frames
        /// (rounds 2 and 3) must be rejected by the ChaCha-Poly AEAD
        /// inside snow. Round 1 (`→ e`) is a bare ephemeral pubkey
        /// with no MAC — any 32-byte string is a valid Curve25519
        /// point, so tampering there is only detected at round 2
        /// decryption. This property covers the MAC-guarded rounds.
        #[test]
        fn prop_handshake_bit_flip_rejected(
            round in 1u8..3,
            offset_seed in any::<usize>(),
            bit_mask in 1u8..=255,
        ) {
            let kp_i = NoiseKeypair::generate().unwrap();
            let kp_r = NoiseKeypair::generate().unwrap();
            let mut initiator = NoiseChannel::initiator(&kp_i).unwrap();
            let mut responder = NoiseChannel::responder(&kp_r).unwrap();

            let m1 = initiator.write_handshake(&[]).unwrap();
            responder.read_handshake(&m1).unwrap();

            let m2_orig = responder.write_handshake(&[]).unwrap();
            if round == 1 {
                let mut tampered = m2_orig.clone();
                let idx = offset_seed % tampered.len();
                tampered[idx] ^= bit_mask;
                prop_assert!(initiator.read_handshake(&tampered).is_err());
                return Ok(());
            }
            initiator.read_handshake(&m2_orig).unwrap();

            // round == 2
            let m3_orig = initiator.write_handshake(&[]).unwrap();
            let mut tampered = m3_orig.clone();
            let idx = offset_seed % tampered.len();
            tampered[idx] ^= bit_mask;
            prop_assert!(responder.read_handshake(&tampered).is_err());
        }

        /// Transport-mode ciphertext tamper: flipping any bit in a
        /// sealed envelope must cause `open` to return Err (ChaCha-Poly
        /// MAC rejection). Protects against on-path relay tampering
        /// after handshake completion.
        #[test]
        fn prop_transport_tamper_rejected(
            plaintext in prop::collection::vec(any::<u8>(), 1..2048),
            offset_seed in any::<usize>(),
            bit_mask in 1u8..=255,
        ) {
            let kp_i = NoiseKeypair::generate().unwrap();
            let kp_r = NoiseKeypair::generate().unwrap();
            let (mut initiator, mut responder) =
                complete_xx_handshake(&kp_i, &kp_r).unwrap();

            let mut env = initiator.seal(&plaintext).unwrap();
            let idx = offset_seed % env.ciphertext.len();
            env.ciphertext[idx] ^= bit_mask;
            prop_assert!(responder.open(&env).is_err());
        }
    }
}
